name: black

on: [push, pull_request]

jobs:
    check-formatting:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
            - uses: psf/black@20.8b1
